# Generated by Django 6.0.1 on 2026-01-17 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_prestamo', models.IntegerField(default=15)),
                ('max_renovaciones', models.IntegerField(default=2)),
                ('max_prestamos_simultaneos', models.IntegerField(default=3)),
                ('multa_por_dia', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('dias_gracia', models.IntegerField(default=0)),
                ('nombre_biblioteca', models.CharField(default='Biblioteca Cecytem', max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horario', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('autor', models.CharField(max_length=200)),
                ('editorial', models.CharField(blank=True, max_length=200, null=True)),
                ('publicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('edicion', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No ficción'), ('ciencia', 'Ciencia'), ('tecnologia', 'Tecnología'), ('historia', 'Historia'), ('matematicas', 'Matemáticas'), ('literatura', 'Literatura'), ('referencia', 'Referencia'), ('arte', 'Arte'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('num_paginas', models.IntegerField(blank=True, null=True)),
                ('idioma', models.CharField(default='Español', max_length=50)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('condicion', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_adquisicion', models.DateField(auto_now_add=True)),
                ('precio_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=200)),
                ('alumno_matricula', models.CharField(max_length=50)),
                ('alumno_grado', models.CharField(blank=True, max_length=50, null=True)),
                ('alumno_grupo', models.CharField(blank=True, max_length=10, null=True)),
                ('alumno_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido'), ('renovado', 'Renovado')], default='activo', max_length=20)),
                ('renovaciones', models.IntegerField(default=0)),
                ('notas_prestamo', models.TextField(blank=True, null=True)),
                ('notas_devolucion', models.TextField(blank=True, null=True)),
                ('tiene_multa', models.BooleanField(default=False)),
                ('monto_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa_pagada', models.BooleanField(default=False)),
                ('prestado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('recibido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.libro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=200)),
                ('alumno_matricula', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso en devolución'), ('daño', 'Daño al libro'), ('perdida', 'Pérdida del libro'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('condonada', 'Condonada')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_multa', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('recibo', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.libro')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.prestamo')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha_multa'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('devolucion', 'Devolución'), ('renovacion', 'Renovación'), ('multa', 'Multa'), ('baja', 'Baja de libro'), ('alta', 'Alta de libro')], max_length=20)),
                ('alumno_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('alumno_matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('usuario_responsable', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.libro')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.prestamo')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
