# Generated by Django 6.0 on 2025-12-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anio_publicacion',
            new_name='publicacion',
        ),
    ]
